version: "3.8"

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    environment:
    - SECRET_KEY= ${PLAY_IT}
  minecraft:
    image: itzg/minecraft-server
    container_name: ${CONTAINER_NAME}
    ports:
      - "${SERVER_PORT}:25565"
      - "${RCON_PORT}:25575"
    environment:
      EULA: "${EULA}"
      TYPE: "${TYPE}"
      VERSION: "${VERSION}"
      MEMORY: "${MEMORY}"
      ENABLE_RCON: "${ENABLE_RCON}"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      ONLINE_MODE: ${ONLINE_MODE}
      ENABLE_WHITELIST: ${ENABLE_WHITELIST}
    volumes:
      - ./data:/data
    restart: unless-stopped
